name: Auto Tag and Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  tag_and_changelog:
    name: Create Tag and Changelog
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python (falls benötigt)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Generate New Tag
      - name: Auto Bump Version
        id: bump
        uses: anothrnick/github-tag-action@v1.51.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: "v" # Optional, falls du einen Präfix nutzen möchtest
          prerelease_suffix: ""

      # 4. Generate Changelog
      - name: Generate Changelog
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          NEW_TAG=${{ steps.bump.outputs.new_tag }}
          echo "## Changelog for $NEW_TAG" > CHANGELOG.md
          git log $LAST_TAG..HEAD --oneline --pretty=format:"- %s" >> CHANGELOG.md
          cat CHANGELOG.md

      # 5. Commit Changelog
      - name: Commit and Push Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update Changelog for ${{ steps.bump.outputs.new_tag }}"
          git push origin main
