name: Create Release Tag and Changelog

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      
      - name: Determine next version
        id: get_version
        run: |
          latest_tag=$(git tag --list | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
             next_version="v1.0.0"
          else
             major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
             minor=$(echo $latest_tag | cut -d. -f2)
             patch=$(echo $latest_tag | cut -d. -f3)
             next_patch=$((patch + 1))
             next_version="v$major.$minor.$next_patch"
          fi
          echo "Next version: $next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV
    
      - name: Create new tag
        run: |
          git tag ${{ env.next_version }}
          git push origin ${{ env.next_version }}

      - name: Set GEM_HOME and PATH
        run: |
          echo "GEM_HOME=$HOME/.gem" >> $GITHUB_ENV
          echo "PATH=$HOME/.gem/bin:$PATH" >> $GITHUB_ENV
          echo "$HOME/.gem/bin" >> $GITHUB_PATH
          
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler
      
      - name: Install github_changelog_generator
        run: gem install github_changelog_generator --no-document
      


      - name: Generate Changelog
        run: github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ env.next_version }}
          body=$(cat CHANGELOG.md)
          gh release create $tag --notes "$body"
